#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 

xset -b
xrdb .Xresources
numlockx on
./.scripts/remapKeys.sh
./.scripts/touchpad.sh
wal -Ra 95
# . "${HOME}/.cache/wal/colors.sh"
color=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)

xsetroot -cursor_name left_ptr

bspc config border_width         0
bspc config focused_border_color "#$color2"
bspc config normal_border_color  "#$color2" 
bspc config window_gap           15 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true 
bspc config initial_polarity 	 second_child

bspc config focus_follows_pointer true

bspc rule -a Musixmatch  state=floating

./.config/bspwm/float.sh & 
# killall -p compton
# compton -bcCG --shadow-exclude '!focused'
# --frame-opacity=0.1
# killall -p dunst
# dunst & 
albert & 
./.config/polybar/start.sh & 
